Feature/generate file by action
shinhancard/dev-portal pull request #84
Opened 2023-08-20 06:11 UTC by jobum97

우선 gradle dependency 들을 입력받아 build.gradle 들 중 일부를 파일로 만드는 부분까지 진행

현재 생각은 기본적인 build.gradle은 스켈레톤 코드로 들어가고 필요한 값들은 변수로 넣어주고

dependencies도 backend 쪽에서 가공을 해서 파일로 떨구는 것이 아닌 fetch action을 통해 입력해주는 방식으로 바꾸는 것이 나을 것 같아 이에 대한 내용은 새로운 이슈로 진행하고자 함

관련 이슈
#58 
#80 

## PR Checklist
Please check if your PR fulfills the following requirements:
- [ ] The commit message follows our guidelines : https://github.com/shinhancard/dev-portal/wiki/Code-of-Conduct
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation 
- [ ] Other

## Rebase 하셨습니까...?
- [ ] Yes
- [ ] No

2023-08-21 00:37 UTC, hellices requested changes

2023-08-21 00:37 UTC, hellices commented on plugins/scaffolder-backend-module-set-dependency/README.md
> +The set-dependency module for [@backstage/plugin-scaffolder-backend](https://www.npmjs.com/package/@backstage/plugin-scaffolder-backend).
plugin-scaffolder-backend 이 플러그인은 왜 들어간건지???

2023-08-21 00:37 UTC, hellices commented on packages/app/src/components/catalog/EntityPage.tsx
> +import {Button, Grid} from '@material-ui/core';
formatter 셋팅이 다른거같아요.

2023-08-21 00:37 UTC, hellices commented on packages/app/package.json
> +    "@backstage/plugin-circleci": "^0.3.19",
circle ci는 안쓸거같은데???

2023-08-21 00:37 UTC, hellices commented on packages/backend/src/providers/scaffolderRouter.ts
> +        logger.info('Dependencies Type list -> nexus에서 목록을 받아오든 DB에서 읽어오든 수정 필요');
todo comment로 변경

2023-08-21 02:10 UTC, jobum97 commented on plugins/scaffolder-backend-module-set-dependency/README.md
> +The set-dependency module for [@backstage/plugin-scaffolder-backend](https://www.npmjs.com/package/@backstage/plugin-scaffolder-backend).
custon action으로 만든 내용을 plugin으로 따로 빼서 구성해보려고 작성중인 코드였는데 잘못 올라갔었습니다.

2023-08-21 02:12 UTC, jobum97 commented on plugins/scaffolder-backend-module-set-dependency/README.md
> +The set-dependency module for [@backstage/plugin-scaffolder-backend](https://www.npmjs.com/package/@backstage/plugin-scaffolder-backend).
[456862e](https://github.com/shinhancard/dev-portal/pull/84/commits/456862ef5136061e5ae7b7f61a1289591eeea512)
수정 완료

2023-08-21 02:17 UTC, jobum97 commented on packages/app/src/components/catalog/EntityPage.tsx
> +import {Button, Grid} from '@material-ui/core';
[110e743](https://github.com/shinhancard/dev-portal/pull/84/commits/110e743a0daa66c46f959e32335d04aa01318328)
수정완료

2023-08-21 02:18 UTC, jobum97 commented on packages/app/package.json
> +    "@backstage/plugin-circleci": "^0.3.19",
[6667a6b](https://github.com/shinhancard/dev-portal/pull/84/commits/6667a6b4509068eaeff3491240cba9ff8a52f1d2)
수정 완료임닷

2023-08-21 02:20 UTC, jobum97 commented on packages/backend/src/providers/scaffolderRouter.ts
> +        logger.info('Dependencies Type list -> nexus에서 목록을 받아오든 DB에서 읽어오든 수정 필요');
[ee47060](https://github.com/shinhancard/dev-portal/pull/84/commits/ee47060f560393e7b8f1921ed10794a0181516f1)
수정완료

2023-08-21 03:47 UTC, hellices commented on packages/app/src/components/catalog/EntityPage.tsx
> +import {Button, Grid} from '@material-ui/core';
packages/app/src/components/catalog/EntityPage.tsx
아직 안맞음

2023-08-21 03:53 UTC, hellices requested changes

2023-08-21 03:53 UTC, hellices commented on packages/backend/src/plugins/scaffolder/actions/create-file/dependcy.ts
> +export const createNewFileAction = () => {
폴더명을 바꾸는게 좋을듯.
scaffolder -> generatedependency ?

2023-08-21 03:53 UTC, hellices commented on packages/app/package.json
> +    "@backstage/plugin-circleci": "^0.3.19",
packages/app/src/components/catalog/EntityPage.tsx -> dependency 남아있음

2023-08-21 04:18 UTC, jobum97 commented on packages/backend/src/plugins/scaffolder/actions/create-file/dependcy.ts
> +export const createNewFileAction = () => {
템플릿 내용을 수정하고 만드는 내용 등 dependency를 generate하는 것 외의 내용도 담는 것으로 
scaffolder 폴더에 안에 generate/dependency로 의미를 담으려 했는데
바꾸는게 나을까요?

2023-08-21 04:20 UTC, jobum97 commented on packages/backend/src/plugins/scaffolder/actions/create-file/dependcy.ts
> +export const createNewFileAction = () => {
[e5ac27b](https://github.com/shinhancard/dev-portal/pull/84/commits/e5ac27bca3f0843f70ee80a35833826ae744f284)
dependency 관련 수정했습니다!

2023-08-21 04:20 UTC, jobum97 commented on packages/app/package.json
> +    "@backstage/plugin-circleci": "^0.3.19",
[e5ac27b](https://github.com/shinhancard/dev-portal/pull/84/commits/e5ac27bca3f0843f70ee80a35833826ae744f284)
추가 수정했습니다!

2023-08-21 05:38 UTC, hellices commented on packages/backend/src/plugins/scaffolder/actions/create-file/dependcy.ts
> +export const createNewFileAction = () => {
scaffolder 가 너무 범용적인거같아서...
generate/dependency로 만들고
다른건 다른 폴더로 하는게 좋을듯? 재사용성도 고려하면

2023-08-21 05:39 UTC, hellices commented on packages/app/package.json
> +    "@backstage/plugin-circleci": "^0.3.19",
Good!

2023-08-21 05:52 UTC, jobum97 commented on packages/backend/src/plugins/scaffolder/actions/create-file/dependcy.ts
> +export const createNewFileAction = () => {
[67f3e45](https://github.com/shinhancard/dev-portal/pull/84/commits/67f3e45640f288ea792a401c567dee7678407da9)
수정완료했습니다~!

2023-08-21 07:46 UTC, hellices approved these changes

2023-08-22 00:47 UTC, dev-shin approved these changes

2023-08-22 00:51 UTC, merged